**Criação de um índice de criminalidade para análises**

O índice é calculado por ano. Para isso, criarei uma tabela para cada ano, em cada coluna referente a um crime está todas as ocorrências de tal crime no ano, e cada linha um município da região administrativa de campinas.

Para o cálculo do índice, seguirei a fórmula desse artigo (com algumas adaptações pois o número de crime analisados pelos autores foi menor): [Definition of Strategies for Crime Prevention and Combat Using Fuzzy Clustering and Formal Concept Analysis](https://www.researchgate.net/publication/320024255_Definition_of_Strategies_for_Crime_Prevention_and_Combat_Using_Fuzzy_Clustering_and_Formal_Concept_Analysis).

A tabela orignal, os pesos dados para cada crime e a fórmula orinal estão abaixo:

| Crime                       | Factor | Weight                                                                                          |
|-----------------------------|--------|-------------------------------------------------------------------------------------------------|
| Theft (victim not present)   | 1      | Theft Weight = (theft dangerousness factor) × (number of theft occurrences)                      |
| Robbery                     | 2      | Robbery Weight = (robbery dangerousness factor) × (number of robbery occurrences)                |
| Homicide                    | 3      | Homicide Weight = (homicide dangerousness factor) × (number of homicide occurrences)             |
| Drug Traffic                | 4      | Drug Traffic Weight = (traffic dangerousness factor) × (number of traffic occurrences)           |

*Table. Calculation of the Danger Factor for each crime type.*

**Fórmula:**


$\text{Danger Level} = \frac{\text{Theft.W} + \text{Robbery.W} + \text{Homicide.W} + \text{Drug.Traffic.W}}{\text{Total.Weight}}$


Como consta no artigo, os pesos para cada crime foram atribuídos por especialistas. "The weighting
of each type of crime was defined using common sense and the opinion of experts"

No nosso trabalho, analisaremos os seguintes crimes:

|Crimes                    |
|---------------------------------|
|Furto de veículo|          
|Furtos outros|             
|Homicídio culposo outros|          
|Homicídio culposo por acidente de trânsito|        
|Latrocínio|         |
|Lesão corporal culposa outras|        
|Lesão corporal culposa por acidente de trânsito|        
|Lesão corporal dolosa|       |
|Homicídio doloso (nº de vítimas)|              
|Tentativa de homicídio|                   
|Total Estupro|                      
|Total de roubos|                     


Como alguns dos crimes que analisaremos não constam na lista de crimes do artigo - e vice-versa -, e alguns deles possuem algumas variações no nossos dados, como homicídio, por exemplo, que nos dados do artigo é unificado, nos nossos dados possui uma separação como visto na tabela acima. Para lidar com isso, faremos algumas modificações nos pesos dados a cada crime.

Para isso, aumentaremos a escala de 1-4 para 1-6. E as explicações para cada peso seguem abaixo de cada crime e seu respectivo crime.

**Pesos mantidos:**

* Furto de veículo (peso 1)
* Furtos outros (peso 1)
* Total de roubos (peso 2)

Para esses crimes, manteremos os pesos dados no artigo, pois acreditamos não haver muita diferença entre o tipo de crime.

**Pesos atualizados por detalhamento de crime**


* Homicídio culposo por acidente de trânsito (peso 4.5)
    * Por envolver conduta negligente, imperita ou imprudente no trânsito, que podem ser causada por outros crimes, como dirigir sob efeito de álcool, acrescentamos 0.5 para ponderar a possível ocorrência - concomitante - de outro crime. Além disso, a pena é de 2 a 4 anos, enquanto a pena de homicídio culposo, de 1 a 3.

* Homicídio culposo outros (peso 4)
    * Como não há a especificação da ocorrência de outro crime concomitantemente, deixaremos 0.5 abaixo do homicídio culposo por acidente
* Homicídio doloso (peso 5)
    * Por haver intenção de realizar o ato acrescentou-se 1 ponto em relação ao homicidio culposo

**Pesos criados para crimes novos**

* Latrocínio (peso 6)
    *
* Lesão corporal culposa outras (peso 2.5)
    * Embora não haja intenção, pode colocar outra vida em risco, porém, de acordo com a lei ainda não é um crime tão grave, então o peso não está maior
* Lesão corporal culposa por acidente de trânsito (peso 3)   
    * Por involver provável imprudência na direção - além de outros crimes que podem estar envolvidos -  acrescentou-se mais 0.5
* Lesão corporal dolosa (peso 3.5)
    * Por haver intenção, adicionou-se 0.5 em relação a LCAT
* Total Estupro (peso 5)
    * Embora não haja morte como no homicídio doloso, estupro é um dos crimes mais graves e além da violação da integridade física, tem a violação da integridade psicológica que resultam em traumas que afetam as vítimas e otras pessoas.
* Tentativa de homicídio (peso 4.5)
    * Por não haver consumação do ato, retiramos 0.5 em relação ao homicídio doloso

Com isso, nossa tabela atualizada com pesos ficou assim:

**Tabela atualizada:**

|Crimes                    |Pesos  |
|---------------------------------|-------------|
|Furto de veículo|       1   |
|Furtos outros|             1 |
|Total de roubos|   2|
|Lesão corporal culposa outras|       2.5 |
|Lesão corporal culposa por acidente de trânsito|    3    |
|Lesão corporal dolosa|       3.5|
|Homicídio culposo outros|        4  |
|Homicídio culposo por acidente de trânsito|     4.5   |
|Tentativa de homicídio|           4.5      |
|Homicídio doloso (nº de vítimas)|     5   |     
|Total Estupro|            5        |  
|Latrocínio|      6   |


**Fórmula atualizada:**

$\text{Índice de Criminalidade} = \frac{\sum_{i=1}^{12} \frac{C_i}{população}  \times P_i}{\sum_{i=1}^{12} P_i}$

Para deixar o índice mais consistente optamos usar crime per capita ao ínves de ocorrências do crime, para evitar que o índice seja afetado pela diferença de tamanhos de população entre os municípios

Como sabe-se, os dados sobre o tamanho da população são coletados em censos que não ocorrem anualmente. Portanto, para solucionar esse problema utilizaremos a estimativa populacional fornecida pelo IBGE (obtidas através do Sidra). [Estimativas - SIDRA](https://sidra.ibge.gov.br/tabela/6579). Para 2022, utilizamos as [prévias do censo](https://www.ibge.gov.br/estatisticas/sociais/populacao/22827-censo-demografico-2022.html?edicao=35938&t=resultados) divulgadas pelo IBGE

# Bibliotecas utilizadas

In [ ]:
import pandas as pd
import numpy as np
from google.colab import files, drive
from functools import reduce

In [ ]:
pip install unidecode

Collecting unidecode
  Downloading Unidecode-1.3.8-py3-none-any.whl.metadata (13 kB)
Downloading Unidecode-1.3.8-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.5/235.5 kB 4.1 MB/s eta 0:00:00
Installing collected packages: unidecode
Successfully installed unidecode-1.3.8

In [ ]:
import unidecode

In [ ]:
!pip install ahpy
import ahpy

# Processamento das bases originais

##### As células de código presentes nessa seção não precisam ser rodadas. Estou mantendo-as aqui com o intuito de documentar o que foi feito.



*   Dados criminais
*   Dados IBGE

As tabelas obtidas no [Portal SSP](https://www.ssp.sp.gov.br/estatistica/dados-mensais) são divididas por crimes e por ano - com as ocorrências criminais computadas mensalmente. Dessa maneira, como estamos analisando 12 crimes, para cada ano existem 12 tabelas. Para facilitar a importação e a análise, criamos uma tabela para cada ano que será analisado (2014, 2016, 2018, 2020, 2022)

Nessas novas tabelas, as colunas em comum (listadas no código abaixo) dos dataframes originais foram mantidas. Retiramos as colunas com as notificações mensais e mantivemos a soma anual da ocorrência de crime no município.

```
def processar(ano):
    files = {
        'furto_veiculo': f'/content/furto_de_veículo_{ano}.csv',
        'furto_outros': f'/content/furto_outros_{ano}.csv',
        'homicidio_culposo_outros': f'/content/homicidio_culposo_outros_{ano}.csv',
        'homicidio_culposo_por_acidente': f'/content/homicidio_culposo_por_acidente_de_trânsito_{ano}.csv',
        'latrocinio': f'/content/latrocinio_{ano}.csv',
        'lesao_culposa_outros': f'/content/lesão_corporal_culposa_outras_{ano}.csv',
        'lesao_culposa_acidente': f'/content/lesão_corporal_culposa_por_acidente_de_trânsito_{ano}.csv',
        'lesao_dolosa': f'/content/lesão_corporal_dolosa_{ano}.csv',
        'vitimas_homicidio': f'/content/nº_de_vítimas_em_homicídio_doloso_3_{ano}.csv',
        'tentativa_homicidio': f'/content/tentativa_de_homicídio_{ano}.csv',
        'total_estupro': f'/content/total_de_estupro_4_{ano}.csv',
        'total_roubos': f'/content/total_de_roubo_outros_1_{ano}.csv'
    }

    dataframes = []

    for tipo_crime, file in files.items():
        df = pd.read_csv(file)
        df = df[['Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária',
                  'Região Geográfica Imediata', 'Nome Região Geográfica Imediata',
                  'Total', 'municipios', 'cod_ibge', 'reg_administrativa', 'reg_metropolitanas']]
        df.rename(columns={'Total': f'{tipo_crime.replace("_", " ").capitalize()} {ano}'}, inplace=True)
        dataframes.append(df)

    colunas_comuns = ['Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária',
                      'Região Geográfica Imediata', 'Nome Região Geográfica Imediata',
                      'municipios', 'cod_ibge', 'reg_administrativa', 'reg_metropolitanas']

    df_combined = reduce(lambda left, right: pd.merge(left, right, on=colunas_comuns, how='outer'), dataframes)

    nova_ordem = colunas_comuns + [f'{tipo_crime.replace("_", " ").capitalize()} {ano}' for tipo_crime in files.keys()]
    df_combined = df_combined[nova_ordem]

    return df_combined
```


Abaixo temos um exemplo de como utilizar a função. Apenas um ano foi exposto pois o processo é o mesmo para os demais.
```
df_2014 = processar(2014)
```


Após processamento as bases foram baixadas para facilitar a importação na hora de utilizar os dados. Abaixo tem-se o exemplo de como o download foi feito para o ano de 2014, mas assim como na função exposta acima, foi-se feito para todos os anos.
```
df_2014.to_csv('df_2014.csv', index=False)

files.download('df_2014.csv')
```

In [ ]:
#@title Fução para importar dados e processar as tabelas
#@markdown

def processar(ano):
    files = {
        'furto_veiculo': f'/content/furto_de_veículo_{ano}.csv',
        'furto_outros': f'/content/furto_outros_{ano}.csv',
        'homicidio_culposo_outros': f'/content/homicidio_culposo_outros_{ano}.csv',
        'homicidio_culposo_por_acidente': f'/content/homicidio_culposo_por_acidente_de_trânsito_{ano}.csv',
        'latrocinio': f'/content/latrocinio_{ano}.csv',
        'lesao_culposa_outros': f'/content/lesão_corporal_culposa_outras_{ano}.csv',
        'lesao_culposa_acidente': f'/content/lesão_corporal_culposa_por_acidente_de_trânsito_{ano}.csv',
        'lesao_dolosa': f'/content/lesão_corporal_dolosa_{ano}.csv',
        'vitimas_homicidio': f'/content/nº_de_vítimas_em_homicídio_doloso_3_{ano}.csv',
        'tentativa_homicidio': f'/content/tentativa_de_homicídio_{ano}.csv',
        'total_estupro': f'/content/total_de_estupro_4_{ano}.csv',
        'total_roubos': f'/content/total_de_roubo_outros_1_{ano}.csv'
    }

    dataframes = []

    for tipo_crime, file in files.items():
        df = pd.read_csv(file)
        df = df[['Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária',
                  'Região Geográfica Imediata', 'Nome Região Geográfica Imediata',
                  'Total', 'municipios', 'cod_ibge', 'reg_administrativa', 'reg_metropolitanas']]
        df.rename(columns={'Total': f'{tipo_crime.replace("_", " ").capitalize()} {ano}'}, inplace=True)
        dataframes.append(df)

    colunas_comuns = ['Região Geográfica Intermediária', 'Nome Região Geográfica Intermediária',
                      'Região Geográfica Imediata', 'Nome Região Geográfica Imediata',
                      'municipios', 'cod_ibge', 'reg_administrativa', 'reg_metropolitanas']

    df_combined = reduce(lambda left, right: pd.merge(left, right, on=colunas_comuns, how='outer'), dataframes)

    nova_ordem = colunas_comuns + [f'{tipo_crime.replace("_", " ").capitalize()} {ano}' for tipo_crime in files.keys()]
    df_combined = df_combined[nova_ordem]

    return df_combined

## 2014

In [ ]:
df_2014 = processar(2014)
df_2014.head(3)

,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,municipios,cod_ibge,reg_administrativa,reg_metropolitanas,Furto veiculo 2014,Furto outros 2014,Homicidio culposo outros 2014,Homicidio culposo por acidente 2014,Latrocinio 2014,Lesao culposa outros 2014,Lesao culposa acidente 2014,Lesao dolosa 2014,Vitimas homicidio 2014,Tentativa homicidio 2014,Total estupro 2014,Total roubos 2014
0,3510,Campinas,350038,Campinas,Campinas,3509502,RA de Campinas,RM de Campinas,4282,19326,5,151,8,79,4073,4116,157,129,251,8949
1,3510,Campinas,350038,Campinas,Holambra,3519055,RA de Campinas,RM de Campinas,8,120,0,2,1,0,40,48,2,0,1,15
2,3510,Campinas,350038,Campinas,Indaiatuba,3520509,RA de Campinas,RM de Campinas,317,1602,0,30,0,171,702,605,9,24,40,644

## 2016

In [ ]:
df_2016 = processar(2016)
df_2016.head(3)

,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,municipios,cod_ibge,reg_administrativa,reg_metropolitanas,Furto veiculo 2016,Furto outros 2016,Homicidio culposo outros 2016,Homicidio culposo por acidente 2016,Latrocinio 2016,Lesao culposa outros 2016,Lesao culposa acidente 2016,Lesao dolosa 2016,Vitimas homicidio 2016,Tentativa homicidio 2016,Total estupro 2016,Total roubos 2016
0,3510,Campinas,350038,Campinas,Campinas,3509502,RA de Campinas,RM de Campinas,4027,17440,4,111,6,186,2905,3955,119,91,276,9451
1,3510,Campinas,350038,Campinas,Holambra,3519055,RA de Campinas,RM de Campinas,9,83,0,0,0,1,41,47,0,3,2,14
2,3510,Campinas,350038,Campinas,Indaiatuba,3520509,RA de Campinas,RM de Campinas,222,1743,0,14,0,53,332,703,5,11,58,627

## 2018

In [ ]:
df_2018 = processar(2018)
df_2018.head(3)

,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,municipios,cod_ibge,reg_administrativa,reg_metropolitanas,Furto veiculo 2018,Furto outros 2018,Homicidio culposo outros 2018,Homicidio culposo por acidente 2018,Latrocinio 2018,Lesao culposa outros 2018,Lesao culposa acidente 2018,Lesao dolosa 2018,Vitimas homicidio 2018,Tentativa homicidio 2018,Total estupro 2018,Total roubos 2018
0,3510,Campinas,350038,Campinas,Campinas,3509502,RA de Campinas,RM de Campinas,3849,16282,5,77,5,22,2264,3314,143,69,269,7034
1,3510,Campinas,350038,Campinas,Holambra,3519055,RA de Campinas,RM de Campinas,7,101,0,0,0,1,38,37,0,0,2,7
2,3510,Campinas,350038,Campinas,Indaiatuba,3520509,RA de Campinas,RM de Campinas,123,1759,0,19,0,5,422,708,7,5,83,403

## 2020

In [ ]:
df_2020 = processar(2020)
df_2020.head(3)

,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,municipios,cod_ibge,reg_administrativa,reg_metropolitanas,Furto veiculo 2020,Furto outros 2020,Homicidio culposo outros 2020,Homicidio culposo por acidente 2020,Latrocinio 2020,Lesao culposa outros 2020,Lesao culposa acidente 2020,Lesao dolosa 2020,Vitimas homicidio 2020,Tentativa homicidio 2020,Total estupro 2020,Total roubos 2020
0,3510,Campinas,350038,Campinas,Campinas,3509502,RA de Campinas,RM de Campinas,2702,11401,1,104,10,39,1378,2814,126,69,231,4999
1,3510,Campinas,350038,Campinas,Holambra,3519055,RA de Campinas,RM de Campinas,7,59,0,1,0,0,24,23,1,2,3,3
2,3510,Campinas,350038,Campinas,Indaiatuba,3520509,RA de Campinas,RM de Campinas,172,1424,0,19,1,4,253,428,3,11,65,312

## 2022

In [ ]:
df_2022 = processar(2022)
df_2022.head(3)

,Região Geográfica Intermediária,Nome Região Geográfica Intermediária,Região Geográfica Imediata,Nome Região Geográfica Imediata,municipios,cod_ibge,reg_administrativa,reg_metropolitanas,Furto veiculo 2022,Furto outros 2022,Homicidio culposo outros 2022,Homicidio culposo por acidente 2022,Latrocinio 2022,Lesao culposa outros 2022,Lesao culposa acidente 2022,Lesao dolosa 2022,Vitimas homicidio 2022,Tentativa homicidio 2022,Total estupro 2022,Total roubos 2022
0,3510,Campinas,350038,Campinas,Campinas,3509502,RA de Campinas,RM de Campinas,3510,17252,2,94,5,57,1336,3548,121,74,312,5568
1,3510,Campinas,350038,Campinas,Holambra,3519055,RA de Campinas,RM de Campinas,11,81,0,1,0,1,22,25,0,0,2,3
2,3510,Campinas,350038,Campinas,Indaiatuba,3520509,RA de Campinas,RM de Campinas,170,1799,0,15,0,11,264,726,7,14,71,282

## Adicionando estimativas populacionais por ano na base

In [ ]:
from os import path

!git clone https://github.com/MurilloYumoto/Analise-Criminal-no-Brasil

path_EST_POP = '/content/Analise-Criminal-no-Brasil/Processamento_base_EST_POP/EST_POP_processada.csv'

fatal: destination path 'Analise-Criminal-no-Brasil' already exists and is not an empty directory.

In [ ]:
path_EST_POP

'/content/Analise-Criminal-no-Brasil/Processamento_base_EST_POP/EST_POP_processada.csv'

In [ ]:
df_pop_2 = pd.read_csv(path_EST_POP)

df_pop_2['Municipio'] = df_pop_2['Municipio'].apply(lambda x: unidecode.unidecode(x))

df_pop_2.head(3)

,Unnamed: 0,Ano,cod_ibge,Municipio,populacao,homens,mulheres,razao_sexo,id_media,dens_demog
0,0,2000,3500105,Adamantina,33484.0,16318.0,17166.0,"105,2","33,7","81,3"
1,1,2000,3500204,Adolfo,3680.0,1868.0,1812.0,97,"32,2","17,4"
2,2,2000,3500303,Aguai,28145.0,14109.0,14036.0,"99,5","30,3","59,3"

In [ ]:
municipios = ['Aguas de Lindoia', 'Amparo','Atibaia','Bom Jesus dos Perdoes','Braganca Paulista',
    'Cabreuva','Campinas','Campo Limpo Paulista','Holambra','Indaiatuba','Itapira','Itatiba',
    'Itupeva','Jaguariuna','Jarinu','Joanopolis','Jundiai','Lindoia','Louveira','Mogi Guacu',
    'Mogi Mirim','Monte Alegre do Sul','Morungaba','Nazare Paulista','Paulinia','Pedra Bela',
    'Pedreira','Pinhalzinho','Piracaia','Santo Antonio de Posse','Serra Negra','Socorro',
    'Tuiuti','Valinhos','Vargem','Varzea Paulista','Vinhedo','Estiva Gerbi']

anos = [2014, 2016, 2018, 2020, 2022]

df_pop_2 = df_pop_2[df_pop_2['Ano'].isin(anos)]
df_pop_2 = df_pop_2[df_pop_2['Municipio'].isin(municipios)]

df_pop_2.rename(columns={'Municipio': 'municipios'}, inplace=True)

df_pop_2 = df_pop_2[['municipios', 'populacao', 'Ano']]

df_pop_2.head(3)

            municipios  populacao   Ano
9034  Aguas de Lindoia    17623.0  2014
9051            Amparo    66789.0  2014
9077           Atibaia   137520.0  2014

In [ ]:
df_pop_2['Ano'] = df_pop_2['Ano'].astype(str)

df_pop_pivot = df_pop_2.pivot(index='municipios', columns='Ano', values='populacao')

df_pop_pivot.columns = [f'Populacao {ano}' for ano in df_pop_pivot.columns]

df_pop_pivot = df_pop_pivot.reset_index()

df_pop_pivot.sort_values(by='municipios', inplace=True)

df_pop_pivot.head()

,municipios,Populacao 2014,Populacao 2016,Populacao 2018,Populacao 2020,Populacao 2022
0,Aguas de Lindoia,17623.0,17753.0,17866.0,17960.0,17925.0
1,Amparo,66789.0,67300.0,67691.0,68032.0,67993.0
2,Atibaia,137520.0,143086.0,148586.0,153965.0,158399.0
3,Bom Jesus dos Perdoes,20407.0,20859.0,21299.0,21693.0,21989.0
4,Braganca Paulista,156920.0,162244.0,167473.0,172439.0,176582.0

In [ ]:
# bases com ocorrências criminais
df_2014 = pd.read_csv('/content/df_2014.csv')
df_2016 = pd.read_csv('/content/df_2016.csv')
df_2018 = pd.read_csv('/content/df_2018.csv')
df_2020 = pd.read_csv('/content/df_2020.csv')
df_2022 = pd.read_csv('/content/df_2022.csv')

# bases com estimativas populacionais
df_pop = pd.read_csv('/content/Estimativas_pop.csv')

In [ ]:
#removendo acentos da coluna municípios e ordenando em ordem alfabética
df_2014['municipios'] = df_2014['municipios'].apply(lambda x: unidecode.unidecode(x))
df_2014 = df_2014.sort_values(by='municipios')

df_2016['municipios'] = df_2016['municipios'].apply(lambda x: unidecode.unidecode(x))
df_2016 = df_2016.sort_values(by='municipios')

df_2018['municipios'] = df_2018['municipios'].apply(lambda x: unidecode.unidecode(x))
df_2018 = df_2018.sort_values(by='municipios')

df_2020['municipios'] = df_2020['municipios'].apply(lambda x: unidecode.unidecode(x))
df_2020 = df_2020.sort_values(by='municipios')

df_2022['municipios'] = df_2022['municipios'].apply(lambda x: unidecode.unidecode(x))
df_2022 = df_2022.sort_values(by='municipios')

In [ ]:
df_pop['Município'] = df_pop['Município'].str.replace(' \(SP\)', '', regex=True)

df_pop.rename(columns={'Município': 'municipios'}, inplace=True)

df_pop['municipios'] = df_pop['municipios'].apply(lambda x: unidecode.unidecode(x))

df_pop.sort_values(by='municipios', inplace=True)

df_pop.rename(columns={'2014': 'Populacao 2014', '2016': 'Populacao 2016', '2018': 'Populacao 2018', '2020': 'Populacao 2020', '2022': 'Populacao 2022'}, inplace=True)

df_pop.head(3)

,municipios,Populacao 2014,Populacao 2016,Populacao 2018,Populacao 2020,Populacao 2022
0,Aguas de Lindoia,18212,18412,18599,18808,18859
1,Amparo,69808,70742,71700,72677,69952
2,Atibaia,135895,138449,141398,144088,171672

In [ ]:
df_2014_pop = pd.merge(df_2014, df_pop[['municipios', 'Populacao 2014']], on='municipios', how='left')
df_2016_pop = pd.merge(df_2016, df_pop[['municipios', 'Populacao 2016']], on='municipios', how='left')
df_2018_pop = pd.merge(df_2018, df_pop[['municipios', 'Populacao 2018']], on='municipios', how='left')
df_2020_pop = pd.merge(df_2020, df_pop[['municipios', 'Populacao 2020']], on='municipios', how='left')
df_2022_pop = pd.merge(df_2022, df_pop[['municipios', 'Populacao 2022']], on='municipios', how='left')

In [ ]:
df_2014_pop.to_csv('df_2014_pop.csv', index=False)
df_2016_pop.to_csv('df_2016_pop.csv', index=False)
df_2018_pop.to_csv('df_2018_pop.csv', index=False)
df_2020_pop.to_csv('df_2020_pop.csv', index=False)
df_2022_pop.to_csv('df_2022_pop.csv', index=False)

In [ ]:
df_2014_pop_2 = pd.merge(df_2014, df_pop_pivot[['municipios', 'Populacao 2014']], on='municipios', how='left')
df_2016_pop_2 = pd.merge(df_2016, df_pop_pivot[['municipios', 'Populacao 2016']], on='municipios', how='left')
df_2018_pop_2 = pd.merge(df_2018, df_pop_pivot[['municipios', 'Populacao 2018']], on='municipios', how='left')
df_2020_pop_2 = pd.merge(df_2020, df_pop_pivot[['municipios', 'Populacao 2020']], on='municipios', how='left')
df_2022_pop_2 = pd.merge(df_2022, df_pop_pivot[['municipios', 'Populacao 2022']], on='municipios', how='left')

In [ ]:
df_2014_pop_2.to_csv('df_2014_pop_2.csv', index=False)
df_2016_pop_2.to_csv('df_2016_pop_2.csv', index=False)
df_2018_pop_2.to_csv('df_2018_pop_2.csv', index=False)
df_2020_pop_2.to_csv('df_2020_pop_2.csv', index=False)
df_2022_pop_2.to_csv('df_2022_pop_2.csv', index=False)

# Importação Final

**Para rodar os código desse notebook é necessário apenas rodar essa célula de importação.**

In [ ]:
df_2014_pop = pd.read_csv('/content/df_2014_pop.csv')
df_2016_pop = pd.read_csv('/content/df_2016_pop.csv')
df_2018_pop = pd.read_csv('/content/df_2018_pop.csv')
df_2020_pop = pd.read_csv('/content/df_2020_pop.csv')
df_2022_pop = pd.read_csv('/content/df_2022_pop.csv')

df_2014_pop_2 = pd.read_csv('/content/df_2014_pop_2.csv')
df_2016_pop_2 = pd.read_csv('/content/df_2016_pop_2.csv')
df_2018_pop_2 = pd.read_csv('/content/df_2018_pop_2.csv')
df_2020_pop_2 = pd.read_csv('/content/df_2020_pop_2.csv')
df_2022_pop_2 = pd.read_csv('/content/df_2022_pop_2.csv')

# Cálculo do índice


| Crime                                             | Peso   | Peso normalizado | Peso AHP 1 | Peso AHP 2 |
|---------------------------------------------------|--------|------------------|------------|------------|
| Furto de veículo                                  | 1      | 0.0263           | 0.0130     | 0.0140     |
| Furtos outros                                     | 1      | 0.0263           | 0.0130     | 0.0140     |
| Total de roubos                                   | 2      | 0.0526           | 0.0160     | 0.0170     |
| Lesão corporal culposa por acidente de trânsito   | 3      | 0.0789           | 0.0280     | 0.0290     |
| Lesão corporal culposa outras                     | 2.5    | 0.0657           | 0.0250     | 0.0270     |
| Lesão corporal dolosa                             | 3.5    | 0.0921           | 0.0400     | 0.0370     |
| Homicídio culposo por acidente de trânsito        | 4.5    | 0.1184           | 0.0700     | 0.0920     |
| Homicídio culposo outros                          | 4      | 0.1052           | 0.0720     | 0.0930     |
| Tentativa de homicídio                            | 4.5    | 0.1184           | 0.1100     | 0.0970     |
| Homicídio doloso (nº de vítimas)                  | 5      | 0.1315           | 0.2200     | 0.1920     |
| Total Estupro                                     | 5      | 0.1315           | 0.1690     | 0.1900     |
| Latrocínio                                        | 6      | 0.1578           | 0.2240     | 0.1990     |

## Definição das fórmulas para cálculo

In [ ]:
def calcular_indice_criminalidade(row, ano, pesos_dict):
    numerador = sum((row[f"{crime} {ano}"] / row[f'Populacao {ano}']) * pesos_dict[crime]  # Access dictionary using key
                    for crime in pesos_dict if f"{crime} {ano}" in row)
    denominador = sum(pesos_dict[crime] for crime in pesos_dict if f"{crime} {ano}" in row)  # Access dictionary using key
    return numerador / denominador if denominador > 0 else 0

In [ ]:
def normalizar_serie(serie):
    min_value = serie.min()
    max_value = serie.max()
    return (serie - min_value) / (max_value - min_value) if (max_value - min_value) > 0 else serie

## Listas par loops

In [ ]:
# anos analisados
anos = ['2014', '2016', '2018', '2020', '2022']

# classificação do índice criminal
bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
labels = ['Muito Baixo', 'Baixo', 'Médio', 'Alto', 'Muito Alto']

## Pesos utilizados para SIDRA e SEADE sem AHP

In [ ]:
pesos = {
    'Furto veiculo': 1,
    'Furto outros': 1,
    'Homicidio culposo outros': 4,
    'Homicidio culposo por acidente': 4.5,
    'Latrocinio': 6,
    'Lesao culposa outros': 2.5,
    'Lesao culposa acidente': 3,
    'Lesao dolosa': 3.5,
    'Vitimas homicidio': 5,
    'Tentativa homicidio': 4.5,
    'Total estupro': 5,
    'Total roubos': 2
}

## SIDRA

#### Os dados populacionais são coletados em censos - ou seja, de 10 em 10 anos -, sendo o último que temos os dados coletados de maneira completa em 2010; embora haja outras fontes que reportem esses dados, é comum considerar os dados do censo para análises. Nesse sentido, como os anos contidos na análise desse trabalho estão entre o último censo completo e o último de 2022 que está imcompleto, os dados utilizados de população no cálculo do índice são estimativas.

### Execução dados SIDRA

In [ ]:
anos = ['2014', '2016', '2018', '2020', '2022']
dataframes = [df_2014_pop, df_2016_pop, df_2018_pop, df_2020_pop, df_2022_pop]

for df, ano in zip(dataframes, anos):
    df['Indice Criminalidade'] = df.apply(lambda row: calcular_indice_criminalidade(row, ano, pesos_dict=pesos), axis=1)

In [ ]:
df_index_2014 = df_2014_pop[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2014'})
df_index_2016 = df_2016_pop[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2016'})
df_index_2018 = df_2018_pop[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2018'})
df_index_2020 = df_2020_pop[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2020'})
df_index_2022 = df_2022_pop[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2022'})

df_final = pd.concat([df_index_2014, df_index_2016['Indice Criminalidade 2016'],
                      df_index_2018['Indice Criminalidade 2018'],
                      df_index_2020['Indice Criminalidade 2020'],
                      df_index_2022['Indice Criminalidade 2022']], axis=1)

In [ ]:
for ano in anos:
    coluna = f'Indice Criminalidade {ano}'
    df_final[f'Indice Criminalidade Normalizado {ano}'] = normalizar_serie(df_final[coluna])

### Resultado

In [ ]:
df_normalizado = df_final[['cod_ibge', 'municipios', 'Indice Criminalidade Normalizado 2014', 'Indice Criminalidade Normalizado 2016', 'Indice Criminalidade Normalizado 2018',
                           'Indice Criminalidade Normalizado 2020', 'Indice Criminalidade Normalizado 2022']]

df_normalizado.head(3)

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Indice Criminalidade Normalizado 2016,Indice Criminalidade Normalizado 2018,Indice Criminalidade Normalizado 2020,Indice Criminalidade Normalizado 2022
0,3500501,Aguas de Lindoia,0.574364,0.302664,0.463143,0.010731,0.120750
1,3501905,Amparo,0.461050,0.532752,0.476568,0.000000,0.149246
2,3504107,Atibaia,0.912955,1.000000,0.757941,0.710423,0.312955

### Classificação

In [ ]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
labels = ['Muito Baixo', 'Baixo', 'Médio', 'Alto', 'Muito Alto']

df_normalizado = df_normalizado.copy()

for ano in anos:
    coluna_normalizada = f'Indice Criminalidade Normalizado {ano}'
    coluna_classificacao = f'Classificacao {ano}'
    df_normalizado[coluna_classificacao] = pd.cut(df_final[coluna_normalizada], bins=bins, labels=labels, include_lowest=True)

df_normalizado = df_normalizado[['cod_ibge', 'municipios', 'Indice Criminalidade Normalizado 2014', 'Classificacao 2014', 'Indice Criminalidade Normalizado 2016',
                                 'Classificacao 2016', 'Indice Criminalidade Normalizado 2018', 'Classificacao 2018', 'Indice Criminalidade Normalizado 2020',
                                 'Classificacao 2020', 'Indice Criminalidade Normalizado 2022', 'Classificacao 2022']]
df_normalizado.head(3)

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Classificacao 2014,Indice Criminalidade Normalizado 2016,Classificacao 2016,Indice Criminalidade Normalizado 2018,Classificacao 2018,Indice Criminalidade Normalizado 2020,Classificacao 2020,Indice Criminalidade Normalizado 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.574364,Médio,0.302664,Baixo,0.463143,Médio,0.010731,Muito Baixo,0.120750,Muito Baixo
1,3501905,Amparo,0.461050,Médio,0.532752,Médio,0.476568,Médio,0.000000,Muito Baixo,0.149246,Muito Baixo
2,3504107,Atibaia,0.912955,Muito Alto,1.000000,Muito Alto,0.757941,Alto,0.710423,Alto,0.312955,Baixo

In [ ]:
#@title baixando df
df_normalizado

df_normalizado.to_csv('df_normalizado.csv', index=False)

files.download('df_normalizado.csv')

## SEADE

#### Ao realizar o cálculo do índice utilizando as estimativas populacionais do SIDRA obtivemos muitos valores extremos no índice (o ou 1). Buscando entender o que causou isso, cruzamos as estimativas do SIDRA com os dados de outras fontes, como prefeituras, por exemplo. Dessa maneira, vimos que as estimativas do SIDRA estavam um pouco desconexas com a realidade. Portanto, buscamos outras estimativas que estivessem mais próximas das outras fontes consultadas.

#### Após isso, realizamos os cálculos e obtivemos resultados melhores.

### Execução dados SEADE

In [ ]:
dataframes = [df_2014_pop_2, df_2016_pop_2, df_2018_pop_2, df_2020_pop_2, df_2022_pop_2]

for df, ano in zip(dataframes, anos):
    df['Indice Criminalidade'] = df.apply(lambda row: calcular_indice_criminalidade(row, ano, pesos_dict=pesos), axis=1)

In [ ]:
df_index_2014_2 = df_2014_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2014'})
df_index_2016_2 = df_2016_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2016'})
df_index_2018_2 = df_2018_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2018'})
df_index_2020_2 = df_2020_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2020'})
df_index_2022_2 = df_2022_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2022'})

df_final_2 = pd.concat([df_index_2014_2, df_index_2016_2['Indice Criminalidade 2016'],
                      df_index_2018_2['Indice Criminalidade 2018'],
                      df_index_2020_2['Indice Criminalidade 2020'],
                      df_index_2022_2['Indice Criminalidade 2022']], axis=1)

In [ ]:
for ano in anos:
    coluna = f'Indice Criminalidade {ano}'
    df_final_2[f'Indice Criminalidade Normalizado {ano}'] = normalizar_serie(df_final_2[coluna])

### Resultados

In [ ]:
df_normalizado_2 = df_final_2[['cod_ibge', 'municipios', 'Indice Criminalidade Normalizado 2014', 'Indice Criminalidade Normalizado 2016', 'Indice Criminalidade Normalizado 2018',
                           'Indice Criminalidade Normalizado 2020', 'Indice Criminalidade Normalizado 2022']]

df_normalizado_2.head(3)

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Indice Criminalidade Normalizado 2016,Indice Criminalidade Normalizado 2018,Indice Criminalidade Normalizado 2020,Indice Criminalidade Normalizado 2022
0,3500501,Aguas de Lindoia,0.563033,0.335446,0.480963,0.013998,0.113259
1,3501905,Amparo,0.465091,0.580210,0.513114,0.022164,0.125659
2,3504107,Atibaia,0.825387,0.916372,0.640838,0.504822,0.344794

### Classificação

In [ ]:
#@title 2
df_normalizado_2 = df_normalizado_2.copy()

for ano in anos:
    coluna_normalizada = f'Indice Criminalidade Normalizado {ano}'
    coluna_classificacao = f'Classificacao {ano}'
    df_normalizado_2[coluna_classificacao] = pd.cut(df_final_2[coluna_normalizada], bins=bins, labels=labels, include_lowest=True)

df_normalizado_2 = df_normalizado_2[['cod_ibge', 'municipios', 'Indice Criminalidade Normalizado 2014', 'Classificacao 2014', 'Indice Criminalidade Normalizado 2016',
                                 'Classificacao 2016', 'Indice Criminalidade Normalizado 2018', 'Classificacao 2018', 'Indice Criminalidade Normalizado 2020',
                                 'Classificacao 2020', 'Indice Criminalidade Normalizado 2022', 'Classificacao 2022']]
df_normalizado_2

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Classificacao 2014,Indice Criminalidade Normalizado 2016,Classificacao 2016,Indice Criminalidade Normalizado 2018,Classificacao 2018,Indice Criminalidade Normalizado 2020,Classificacao 2020,Indice Criminalidade Normalizado 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.563033,Médio,0.335446,Baixo,0.480963,Médio,0.013998,Muito Baixo,0.113259,Muito Baixo
1,3501905,Amparo,0.465091,Médio,0.580210,Médio,0.513114,Médio,0.022164,Muito Baixo,0.125659,Muito Baixo
2,3504107,Atibaia,0.825387,Muito Alto,0.916372,Muito Alto,0.640838,Alto,0.504822,Médio,0.344794,Baixo
3,3507100,Bom Jesus dos Perdoes,0.263848,Baixo,0.464167,Médio,0.493944,Médio,0.353559,Baixo,0.412630,Médio
4,3507605,Braganca Paulista,0.780567,Alto,0.680555,Alto,0.568227,Médio,0.386751,Baixo,0.387877,Baixo
5,3508405,Cabreuva,0.312697,Baixo,0.246863,Baixo,0.303375,Baixo,0.245103,Baixo,0.199181,Muito Baixo
6,3509502,Campinas,1.000000,Muito Alto,1.000000,Muito Alto,1.000000,Muito Alto,0.981189,Muito Alto,1.000000,Muito Alto
7,3509601,Campo Limpo Paulista,0.495505,Médio,0.784689,Alto,0.887914,Muito Alto,0.512760,Médio,0.553175,Médio
8,3557303,Estiva Gerbi,0.608693,Alto,0.645365,Alto,0.529972,Médio,0.806230,Muito Alto,0.944173,Muito Alto
9,3519055,Holambra,0.309385,Baixo,0.271997,Baixo,0.281978,Baixo,0.034219,Muito Baixo,0.000000,Muito Baixo
10,3520509,Indaiatuba,0.305560,Baixo,0.234964,Baixo,0.350033,Baixo,0.151262,Muito Baixo,0.266889,Baixo
11,3522604,Itapira,0.638050,Alto,0.617350,Alto,0.673722,Alto,0.674267,Alto,0.504070,Médio
12,3523404,Itatiba,0.424705,Médio,0.541222,Médio,0.590737,Médio,0.344947,Baixo,0.395166,Baixo
13,3524006,Itupeva,0.418148,Médio,0.427954,Médio,0.518141,Médio,0.287972,Baixo,0.338667,Baixo
14,3524709,Jaguariuna,0.793611,Alto,0.687744,Alto,0.974157,Muito Alto,0.453879,Médio,0.901527,Muito Alto
15,3525201,Jarinu,0.259318,Baixo,0.307115,Baixo,0.330179,Baixo,0.511745,Médio,0.310930,Baixo
16,3525508,Joanopolis,0.229975,Baixo,0.315891,Baixo,0.627294,Alto,0.363902,Baixo,0.541849,Médio
17,3525904,Jundiai,0.615428,Alto,0.582909,Médio,0.488451,Médio,0.385045,Baixo,0.493064,Médio
18,3527009,Lindoia,0.402114,Médio,0.422275,Médio,0.308176,Baixo,1.000000,Muito Alto,0.206135,Baixo
19,3527306,Louveira,0.338423,Baixo,0.378268,Baixo,0.374101,Baixo,0.261880,Baixo,0.110674,Muito Baixo
20,3530706,Mogi Guacu,0.760428,Alto,0.878685,Muito Alto,0.934286,Muito Alto,0.797108,Alto,0.797403,Alto
21,3530805,Mogi Mirim,0.859456,Muito Alto,0.913427,Muito Alto,0.914959,Muito Alto,0.792533,Alto,0.772519,Alto
22,3531209,Monte Alegre do Sul,0.033801,Muito Baixo,0.000000,Muito Baixo,0.000000,Muito Baixo,0.000000,Muito Baixo,0.114315,Muito Baixo
23,3532009,Morungaba,0.194920,Muito Baixo,0.116807,Muito Baixo,0.311039,Baixo,0.104062,Muito Baixo,0.099340,Muito Baixo
24,3532405,Nazare Paulista,0.386821,Baixo,0.507893,Médio,0.641684,Alto,0.310420,Baixo,0.354692,Baixo
25,3536505,Paulinia,0.778892,Alto,0.784891,Alto,0.815814,Muito Alto,0.723244,Alto,0.734889,Alto
26,3536802,Pedra Bela,0.157674,Muito Baixo,0.144654,Muito Baixo,0.108247,Muito Baixo,0.076244,Muito Baixo,0.009689,Muito Baixo
27,3537107,Pedreira,0.690278,Alto,0.891207,Muito Alto,0.472056,Médio,0.108087,Muito Baixo,0.097819,Muito Baixo
28,3538204,Pinhalzinho,0.000000,Muito Baixo,0.075110,Muito Baixo,0.087632,Muito Baixo,0.182285,Muito Baixo,0.175407,Muito Baixo
29,3538600,Piracaia,0.500278,Médio,0.291489,Baixo,0.460660,Médio,0.173455,Muito Baixo,0.346695,Baixo
30,3548005,Santo Antonio de Posse,0.219810,Baixo,0.326234,Baixo,0.430852,Médio,0.368819,Baixo,0.395347,Baixo
31,3551603,Serra Negra,0.373478,Baixo,0.560477,Médio,0.530310,Médio,0.457688,Médio,0.240794,Baixo
32,3552106,Socorro,0.284483,Baixo,0.243390,Baixo,0.235466,Baixo,0.183056,Muito Baixo,0.071892,Muito Baixo
33,3554953,Tuiuti,0.486376,Médio,0.388865,Baixo,0.161523,Muito Baixo,0.109111,Muito Baixo,0.368869,Baixo
34,3556206,Valinhos,0.467055,Médio,0.414197,Médio,0.524713,Médio,0.445533,Médio,0.304884,Baixo
35,3556354,Vargem,0.382715,Baixo,0.322954,Baixo,0.325257,Baixo,0.241444,Baixo,0.239912,Baixo
36,3556503,Varzea Paulista,0.396917,Baixo,0.557003,Médio,0.425272,Médio,0.365506,Baixo,0.445746,Médio
37,3556701,Vinhedo,0.641108,Alto,0.444606,Médio,0.539378,Médio,0.302284,Baixo,0.330150,Baixo

## Método Analítico Hierárquico (AHP)



## Descrição do Método
O método AHP é uma técnica multicritério amplamente utilizada para tomar decisões complexas envolvendo múltiplos fatores. Ele organiza o problema em uma estrutura hierárquica, começando pelo objetivo principal, passando pelos critérios e subcritérios (se aplicável), até as alternativas a serem avaliadas.

### Passos Principais do AHP

---

### 1. Estruturação Hierárquica
Definir a hierarquia do problema, que inclui:
- **Objetivo Principal**: A meta que se deseja alcançar.
- **Critérios de Decisão**: Fatores que influenciam a decisão.
- **Subcritérios**: Detalhamentos dos critérios principais.
- **Alternativas**: Opções disponíveis para a decisão.

### 2. Construção da Matriz de Comparação
A matriz de comparação $A$ é formada a partir das comparações por pares entre os elementos (critérios ou alternativas). Cada entrada $a_{ij}$ da matriz representa a importância relativa do elemento $i$ em relação ao elemento $j$, utilizando a **Escala de Saaty**:

- **Escala de Saaty**:
  - 1: Importância igual.
  - 3: Importância moderada.
  - 5: Importância forte.
  - 7: Importância muito forte.
  - 9: Importância extrema.
  - Os recíprocos (e.g., $\frac{1}{3}$, $\frac{1}{5}$) são usados para relações inversas.

Além desses valores existem os intermediários: 2, 4, 6, 8.

- **Propriedades da Matriz**:
  - $a_{ij} = \frac{1}{a_{ji}}$ (reciprocidade).
  - $a_{ii} = 1$ (elementos comparados consigo mesmos).

### 3. Normalização da Matriz
Para calcular os pesos relativos:
1. **Soma-se os valores de cada coluna**:
   $$
   \text{soma}_j = \sum_{i=1}^{n} a_{ij}
   $$
2. **Dividi cada elemento $a_{ij}$ pelo total da coluna correspondente**:
   $$
   a'_{ij} = \frac{a_{ij}}{\text{soma}_j}
   $$
   Isso transforma os valores de cada coluna em frações que somam 1.

### 4. Cálculo do Vetor de Prioridade (Pesos Relativos)
Os pesos relativos $w$ são calculados como a média das linhas normalizadas:
$$
w_i = \frac{1}{n} \sum_{j=1}^{n} a'_{ij}
$$
O vetor resultante $w$ representa os pesos relativos de cada elemento.

### 5. Verificação de Consistência
Para garantir a confiabilidade das comparações, o AHP avalia a consistência da matriz utilizando o **Índice de Consistência (CI)** e a **Razão de Consistência (CR)**:

- **Índice de Consistência (CI)**:
  $$
  CI = \frac{\lambda_{\text{max}} - n}{n - 1}
  $$
  - $\lambda_{\text{max}}$: maior valor próprio da matriz original.
  - $n$: número de elementos na matriz.

- **Razão de Consistência (CR)**:
  $$
  CR = \frac{CI}{RI}
  $$
  - $RI$: Índice Aleatório de Consistência (valor tabelado).

Se $CR \leq 0.1$, a matriz é considerada **consistente**. Caso contrário, as comparações devem ser revisadas.


#### Implementação com `ahpy`
O código utiliza a biblioteca `ahpy` para automatizar:
- **Construção da Matriz de Comparação**: Definida através de dicionários que especificam as comparações por pares.
- **Cálculo dos Pesos Relativos**: Normalização da matriz e cálculo dos vetores próprios.
- **Verificação de Consistência**: Cálculo automático do índice de consistência (CR). Se $CR > 0.1$, as comparações devem ser revisadas.

### Utilizando apenas Gravidade do crime como critério para criação de pesos

In [ ]:
crimes = [
    'Furto de veículo',
    'Furtos outros',
    'Total de roubos',
    'Lesão corporal culposa por acidente de trânsito',
    'Lesão corporal culposa outras',
    'Lesão corporal dolosa',
    'Homicídio culposo por acidente de trânsito',
    'Homicídio culposo outros',
    'Tentativa de homicídio',
    'Homicídio doloso (nº de vítimas)',
    'Total Estupro',
    'Latrocínio'
]


comparacoes_gravidade = {
    # Comparações envolvendo 'Furto de veículo'
    ('Furto de veículo', 'Furtos outros'): 1,
    ('Furto de veículo', 'Total de roubos'): 1/2,
    ('Furto de veículo', 'Lesão corporal culposa por acidente de trânsito'): 1/4,
    ('Furto de veículo', 'Lesão corporal culposa outras'): 1/4,
    ('Furto de veículo', 'Lesão corporal dolosa'): 1/5,
    ('Furto de veículo', 'Homicídio culposo por acidente de trânsito'): 1/6,
    ('Furto de veículo', 'Homicídio culposo outros'): 1/6,
    ('Furto de veículo', 'Tentativa de homicídio'): 1/6,
    ('Furto de veículo', 'Homicídio doloso (nº de vítimas)'): 1/7,
    ('Furto de veículo', 'Total Estupro'): 1/8,
    ('Furto de veículo', 'Latrocínio'): 1/9,

    # Comparações envolvendo 'Furtos outros'
    ('Furtos outros', 'Total de roubos'): 1/2,
    ('Furtos outros', 'Lesão corporal culposa por acidente de trânsito'): 1/4,
    ('Furtos outros', 'Lesão corporal culposa outras'): 1/4,
    ('Furtos outros', 'Lesão corporal dolosa'): 1/5,
    ('Furtos outros', 'Homicídio culposo por acidente de trânsito'): 1/6,
    ('Furtos outros', 'Homicídio culposo outros'): 1/6,
    ('Furtos outros', 'Tentativa de homicídio'): 1/6,
    ('Furtos outros', 'Homicídio doloso (nº de vítimas)'): 1/7,
    ('Furtos outros', 'Total Estupro'): 1/8,
    ('Furtos outros', 'Latrocínio'): 1/9,

    # Comparações envolvendo 'Total de roubos'
    ('Total de roubos', 'Lesão corporal culposa por acidente de trânsito'): 1/3,
    ('Total de roubos', 'Lesão corporal culposa outras'): 1/3,
    ('Total de roubos', 'Lesão corporal dolosa'): 1/4,
    ('Total de roubos', 'Homicídio culposo por acidente de trânsito'): 1/6,
    ('Total de roubos', 'Homicídio culposo outros'): 1/6,
    ('Total de roubos', 'Tentativa de homicídio'): 1/7,
    ('Total de roubos', 'Homicídio doloso (nº de vítimas)'): 1/8,
    ('Total de roubos', 'Total Estupro'): 1/8,
    ('Total de roubos', 'Latrocínio'): 1/9,

    # Comparações envolvendo 'Lesão corporal culposa por acidente de trânsito'
    ('Lesão corporal culposa por acidente de trânsito', 'Lesão corporal culposa outras'): 1,
    ('Lesão corporal culposa por acidente de trânsito', 'Lesão corporal dolosa'): 1/2,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio culposo por acidente de trânsito'): 1/5,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio culposo outros'): 1/5,
    ('Lesão corporal culposa por acidente de trânsito', 'Tentativa de homicídio'): 1/3,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio doloso (nº de vítimas)'): 1/6,
    ('Lesão corporal culposa por acidente de trânsito', 'Total Estupro'): 1/8,
    ('Lesão corporal culposa por acidente de trânsito', 'Latrocínio'): 1/9,

    # Comparações envolvendo 'Lesão corporal culposa outras'
    ('Lesão corporal culposa outras', 'Lesão corporal dolosa'): 1/3,
    ('Lesão corporal culposa outras', 'Homicídio culposo por acidente de trânsito'): 1/5,
    ('Lesão corporal culposa outras', 'Homicídio culposo outros'): 1/5,
    ('Lesão corporal culposa outras', 'Tentativa de homicídio'): 1/7,
    ('Lesão corporal culposa outras', 'Homicídio doloso (nº de vítimas)'): 1/8,
    ('Lesão corporal culposa outras', 'Total Estupro'): 1/8,
    ('Lesão corporal culposa outras', 'Latrocínio'): 1/9,

    # Comparações envolvendo 'Lesão corporal dolosa'
    ('Lesão corporal dolosa', 'Homicídio culposo por acidente de trânsito'): 1/3,
    ('Lesão corporal dolosa', 'Homicídio culposo outros'): 1/3,
    ('Lesão corporal dolosa', 'Tentativa de homicídio'): 1/4,
    ('Lesão corporal dolosa', 'Homicídio doloso (nº de vítimas)'): 1/6,
    ('Lesão corporal dolosa', 'Total Estupro'): 1/6,
    ('Lesão corporal dolosa', 'Latrocínio'): 1/7,

    # Comparações envolvendo 'Homicídio culposo por acidente de trânsito'
    ('Homicídio culposo por acidente de trânsito', 'Homicídio culposo outros'): 1,
    ('Homicídio culposo por acidente de trânsito', 'Tentativa de homicídio'): 1/3,
    ('Homicídio culposo por acidente de trânsito', 'Homicídio doloso (nº de vítimas)'): 1/4,
    ('Homicídio culposo por acidente de trânsito', 'Total Estupro'): 1/5,
    ('Homicídio culposo por acidente de trânsito', 'Latrocínio'): 1/6,

    # Comparações envolvendo 'Homicídio culposo outros'
    ('Homicídio culposo outros', 'Tentativa de homicídio'): 1/3,
    ('Homicídio culposo outros', 'Homicídio doloso (nº de vítimas)'): 1/4,
    ('Homicídio culposo outros', 'Total Estupro'): 1/4,
    ('Homicídio culposo outros', 'Latrocínio'): 1/5,

    # Comparações envolvendo 'Tentativa de homicídio'
    ('Tentativa de homicídio', 'Homicídio doloso (nº de vítimas)'): 1/2,
    ('Tentativa de homicídio', 'Total Estupro'): 1/2,
    ('Tentativa de homicídio', 'Latrocínio'): 1/4,

    # Comparações envolvendo 'Homicídio doloso (nº de vítimas)'
    ('Homicídio doloso (nº de vítimas)', 'Total Estupro'): 2,
    ('Homicídio doloso (nº de vítimas)', 'Latrocínio'): 3,

    # Comparações envolvendo 'Total Estupro'
    ('Total Estupro', 'Latrocínio'): 1/2
}

# Criar o objeto AHP para Gravidade do Crime
gravidade_ahp = ahpy.Compare(
    name='Gravidade do Crime',
    comparisons=comparacoes_gravidade,
    precision=3,
    random_index='saaty'
)

# Verificar a consistência das comparações de Gravidade do Crime
print(f"Consistency Ratio (Gravidade do Crime): {gravidade_ahp.consistency_ratio:.4f}")
if gravidade_ahp.consistency_ratio > 0.1:
    print("A consistência das comparações de Gravidade do Crime é baixa. Revise as comparações.")
else:
    print("A consistência das comparações de Gravidade do Crime está adequada.")

# Obter os pesos dentro do critério Gravidade do Crime
pesos_gravidade = gravidade_ahp.target_weights
print("\nPesos dentro do Critério: Gravidade do Crime")
for crime, peso in sorted(pesos_gravidade.items(), key=lambda x: x[1], reverse=True):
    print(f"{crime}: {peso:.4f}")

# Pesos finais (já que há apenas um critério, os pesos de gravidade são os pesos finais)
pesos_finais = pesos_gravidade

Consistency Ratio (Gravidade do Crime): 0.0800
A consistência das comparações de Gravidade do Crime está adequada.

Pesos dentro do Critério: Gravidade do Crime
Latrocínio: 0.2240
Homicídio doloso (nº de vítimas): 0.2200
Total Estupro: 0.1690
Tentativa de homicídio: 0.1100
Homicídio culposo outros: 0.0720
Homicídio culposo por acidente de trânsito: 0.0700
Lesão corporal dolosa: 0.0400
Lesão corporal culposa por acidente de trânsito: 0.0280
Lesão corporal culposa outras: 0.0250
Total de roubos: 0.0160
Furto de veículo: 0.0130
Furtos outros: 0.0130

In [ ]:
pesos_AHP = {
    'Furto veiculo': 0.0130,
    'Furto outros': 0.0130,
    'Homicidio culposo outros': 0.068,
    'Homicidio culposo por acidente': 0.067,
    'Latrocinio':  0.2250,
    'Lesao culposa outros': 0.0250,
    'Lesao culposa acidente': 0.0280,
    'Lesao dolosa': 0.0410,
    'Vitimas homicidio': 0.2210,
    'Tentativa homicidio': 0.1150,
    'Total estupro': 0.1690,
    'Total roubos': 0.0160
}

In [ ]:
dataframes = [df_2014_pop_2, df_2016_pop_2, df_2018_pop_2, df_2020_pop_2, df_2022_pop_2]

for df, ano in zip(dataframes, anos):
    df['Indice Criminalidade'] = df.apply(lambda row: calcular_indice_criminalidade(row, ano, pesos_AHP), axis=1)

In [ ]:
df_index_2014_2 = df_2014_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2014'})
df_index_2016_2 = df_2016_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2016'})
df_index_2018_2 = df_2018_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2018'})
df_index_2020_2 = df_2020_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2020'})
df_index_2022_2 = df_2022_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2022'})

df_final_2 = pd.concat([df_index_2014_2, df_index_2016_2['Indice Criminalidade 2016'],
                      df_index_2018_2['Indice Criminalidade 2018'],
                      df_index_2020_2['Indice Criminalidade 2020'],
                      df_index_2022_2['Indice Criminalidade 2022']], axis=1)

In [ ]:
df_final_2

In [ ]:
for ano in anos:
    coluna = f'Indice Criminalidade {ano}'
    df_final_2[f'Indice Criminalidade Normalizado {ano}'] = normalizar_serie(df_final_2[coluna])

In [ ]:
# multiplicar resultados por 1000
for ano in anos:
    coluna = f'Indice Criminalidade {ano}'
    df_final_2[coluna] = df_final_2[coluna] * 1000

df_final_2

,cod_ibge,municipios,Indice Criminalidade 2014,Indice Criminalidade 2016,Indice Criminalidade 2018,Indice Criminalidade 2020,Indice Criminalidade 2022,Indice Criminalidade Normalizado 2014,Indice Criminalidade Normalizado 2016,Indice Criminalidade Normalizado 2018,Indice Criminalidade Normalizado 2020,Indice Criminalidade Normalizado 2022
0,3500501,Aguas de Lindoia,0.612733,0.457943,0.463043,0.256759,0.271026,0.644288,0.400365,0.616027,0.089407,0.150255
1,3501905,Amparo,0.539460,0.523800,0.435118,0.243862,0.285714,0.466896,0.570811,0.531249,0.037027,0.193373
2,3504107,Atibaia,0.727712,0.678808,0.494566,0.356432,0.357189,0.922644,0.971989,0.711726,0.494225,0.403189
3,3507100,Bom Jesus dos Perdoes,0.450033,0.495885,0.446898,0.337375,0.452092,0.250398,0.498562,0.567013,0.416826,0.681780
4,3507605,Braganca Paulista,0.679705,0.575458,0.440645,0.306480,0.358364,0.806423,0.704508,0.548030,0.291348,0.406639
5,3508405,Cabreuva,0.494016,0.421995,0.366487,0.299919,0.353333,0.356879,0.307325,0.322892,0.264698,0.391869
6,3509502,Campinas,0.759664,0.689630,0.589520,0.441448,0.560495,1.000000,1.000000,1.000000,0.839509,1.000000
7,3509601,Campo Limpo Paulista,0.531069,0.596282,0.541164,0.337507,0.425451,0.446583,0.758404,0.853196,0.417362,0.603574
8,3557303,Estiva Gerbi,0.596290,0.610849,0.456971,0.435962,0.544733,0.604480,0.796103,0.597594,0.817229,0.953729
9,3519055,Holambra,0.477975,0.395541,0.322445,0.245340,0.219841,0.318045,0.238860,0.189186,0.043029,0.000000
10,3520509,Indaiatuba,0.444103,0.385064,0.374809,0.262202,0.327500,0.236042,0.211744,0.348158,0.111515,0.316037
11,3522604,Itapira,0.594226,0.545607,0.497769,0.387408,0.393984,0.599482,0.627249,0.721453,0.620029,0.511200
12,3523404,Itatiba,0.543003,0.515136,0.429831,0.293965,0.360222,0.475474,0.548387,0.515199,0.240519,0.412092
13,3524006,Itupeva,0.537466,0.492965,0.434241,0.286242,0.359557,0.462069,0.491006,0.528588,0.209151,0.410141
14,3524709,Jaguariuna,0.654653,0.552147,0.584442,0.327268,0.526885,0.745773,0.644177,0.984584,0.375775,0.901335
15,3525201,Jarinu,0.505661,0.432264,0.412955,0.389947,0.385802,0.385070,0.333904,0.463966,0.630343,0.487184
16,3525508,Joanopolis,0.490534,0.459534,0.484753,0.292354,0.494625,0.348449,0.404482,0.681937,0.233975,0.806637
17,3525904,Jundiai,0.593006,0.512778,0.410729,0.303560,0.386038,0.596529,0.542285,0.457208,0.279487,0.487875
18,3527009,Lindoia,0.489646,0.493498,0.353282,0.480964,0.263285,0.346301,0.492385,0.282805,1.000000,0.127530
19,3527306,Louveira,0.481974,0.443344,0.345701,0.284785,0.299698,0.327726,0.362580,0.259790,0.203233,0.234423
20,3530706,Mogi Guacu,0.639978,0.643009,0.561303,0.403010,0.493885,0.710246,0.879338,0.914334,0.683397,0.804465
21,3530805,Mogi Mirim,0.697438,0.642344,0.545292,0.409159,0.485231,0.849352,0.877616,0.865727,0.708370,0.779059
22,3531209,Monte Alegre do Sul,0.346603,0.303250,0.276592,0.234745,0.317695,0.000000,0.000000,0.049981,0.000000,0.287254
23,3532009,Morungaba,0.447508,0.339213,0.343214,0.257744,0.267591,0.244285,0.093076,0.252239,0.093411,0.140171
24,3532405,Nazare Paulista,0.587981,0.588723,0.543734,0.325781,0.426074,0.584363,0.738838,0.860998,0.369734,0.605402
25,3536505,Paulinia,0.694787,0.619743,0.526327,0.386577,0.485839,0.842936,0.819122,0.808151,0.616657,0.780845
26,3536802,Pedra Bela,0.403143,0.401160,0.323441,0.243378,0.304229,0.136882,0.253402,0.192208,0.035063,0.247724
27,3537107,Pedreira,0.602065,0.647000,0.406168,0.238120,0.266618,0.618459,0.889667,0.443361,0.013709,0.137315
28,3538204,Pinhalzinho,0.351729,0.344539,0.260129,0.271902,0.328380,0.012411,0.106860,0.000000,0.150912,0.318620
29,3538600,Piracaia,0.567373,0.429377,0.463752,0.306653,0.378402,0.534473,0.326431,0.618179,0.292051,0.465460
30,3548005,Santo Antonio de Posse,0.461563,0.456264,0.425497,0.299609,0.392804,0.278311,0.396019,0.502042,0.263439,0.507738
31,3551603,Serra Negra,0.513554,0.557891,0.425780,0.340059,0.328853,0.404180,0.659041,0.502900,0.427728,0.320007
32,3552106,Socorro,0.450725,0.393489,0.351173,0.290390,0.253332,0.252075,0.233548,0.276400,0.225998,0.098312
33,3554953,Tuiuti,0.561468,0.488764,0.279446,0.252664,0.365848,0.520178,0.480132,0.058646,0.072776,0.428607
34,3556206,Valinhos,0.525309,0.451859,0.414272,0.309613,0.326827,0.432639,0.384618,0.467963,0.304072,0.314060
35,3556354,Vargem,0.547077,0.486916,0.442674,0.291822,0.344545,0.485337,0.475350,0.554189,0.231815,0.366073
36,3556503,Varzea Paulista,0.488519,0.512358,0.401065,0.315670,0.388556,0.343572,0.541198,0.427867,0.328671,0.495268
37,3556701,Vinhedo,0.603905,0.462442,0.415626,0.290153,0.347929,0.622914,0.412007,0.472075,0.225035,0.376006

In [ ]:
df_final_AHP = df_final_2.copy()

for ano in anos:
    coluna_index = f'Indice Criminalidade {ano}'
    coluna_classificacao = f'Classificacao {ano}'
    df_final_AHP[coluna_classificacao] = pd.cut(df_final_AHP[coluna_index], bins=bins, labels=labels, include_lowest=True)

df_final_AHP = df_final_AHP[['cod_ibge', 'municipios', 'Indice Criminalidade 2014', 'Classificacao 2014', 'Indice Criminalidade 2016',
                                 'Classificacao 2016', 'Indice Criminalidade 2018', 'Classificacao 2018', 'Indice Criminalidade 2020',
                                 'Classificacao 2020', 'Indice Criminalidade 2022', 'Classificacao 2022']]
df_final_AHP.head(3)

,cod_ibge,municipios,Indice Criminalidade 2014,Classificacao 2014,Indice Criminalidade 2016,Classificacao 2016,Indice Criminalidade 2018,Classificacao 2018,Indice Criminalidade 2020,Classificacao 2020,Indice Criminalidade 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.612733,Alto,0.457943,Médio,0.463043,Médio,0.256759,Baixo,0.271026,Baixo
1,3501905,Amparo,0.539460,Médio,0.523800,Médio,0.435118,Médio,0.243862,Baixo,0.285714,Baixo
2,3504107,Atibaia,0.727712,Alto,0.678808,Alto,0.494566,Médio,0.356432,Baixo,0.357189,Baixo

### Utilizando gravidade dos crimes + impacto social para cálculo dos pesos

In [ ]:
criterios = ['Gravidade do Crime', 'Impacto Social']

# Comparação por pares dos critérios principais
comparacoes_criterios = {
    ('Gravidade do Crime', 'Impacto Social'): 2
}

# Comparações por pares para Impacto Social
comparacoes_impacto_social = {
    ('Furto de veículo', 'Furtos outros'): 1,
    ('Furto de veículo', 'Total de roubos'): 1/2,
    ('Furto de veículo', 'Lesão corporal culposa por acidente de trânsito'): 1/3,
    ('Furto de veículo', 'Lesão corporal culposa outras'): 1/3,
    ('Furto de veículo', 'Lesão corporal dolosa'): 1/3,
    ('Furto de veículo', 'Homicídio culposo por acidente de trânsito'): 1/8,
    ('Furto de veículo', 'Homicídio culposo outros'): 1/8,
    ('Furto de veículo', 'Tentativa de homicídio'): 1/5,
    ('Furto de veículo', 'Homicídio doloso (nº de vítimas)'): 1/8,
    ('Furto de veículo', 'Total Estupro'): 1/9,
    ('Furto de veículo', 'Latrocínio'): 1/8,

     # Comparações envolvendo 'Furtos outros'
    ('Furtos outros', 'Total de roubos'): 1/2,
    ('Furtos outros', 'Lesão corporal culposa por acidente de trânsito'): 1/3,
    ('Furtos outros', 'Lesão corporal culposa outras'): 1/3,
    ('Furtos outros', 'Lesão corporal dolosa'): 1/3,
    ('Furtos outros', 'Homicídio culposo por acidente de trânsito'): 1/8,
    ('Furtos outros', 'Homicídio culposo outros'): 1/8,
    ('Furtos outros', 'Tentativa de homicídio'): 1/5,
    ('Furtos outros', 'Homicídio doloso (nº de vítimas)'): 1/8,
    ('Furtos outros', 'Total Estupro'): 1/9,
    ('Furtos outros', 'Latrocínio'): 1/8,

    # Comparações envolvendo 'Total de roubos'
    ('Total de roubos', 'Lesão corporal culposa por acidente de trânsito'): 1/2,
    ('Total de roubos', 'Lesão corporal culposa outras'): 1/2,
    ('Total de roubos', 'Lesão corporal dolosa'): 1/2,
    ('Total de roubos', 'Homicídio culposo por acidente de trânsito'): 1/7,
    ('Total de roubos', 'Homicídio culposo outros'): 1/7,
    ('Total de roubos', 'Tentativa de homicídio'): 1/6,
    ('Total de roubos', 'Homicídio doloso (nº de vítimas)'): 1/7,
    ('Total de roubos', 'Total Estupro'): 1/9,
    ('Total de roubos', 'Latrocínio'): 1/7,

    # Comparações envolvendo 'Lesão corporal culposa por acidente de trânsito'
    ('Lesão corporal culposa por acidente de trânsito', 'Lesão corporal culposa outras'): 1,
    ('Lesão corporal culposa por acidente de trânsito', 'Lesão corporal dolosa'): 1,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio culposo por acidente de trânsito'): 1/5,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio culposo outros'): 1/5,
    ('Lesão corporal culposa por acidente de trânsito', 'Tentativa de homicídio'): 1/2,
    ('Lesão corporal culposa por acidente de trânsito', 'Homicídio doloso (nº de vítimas)'): 1/5,
    ('Lesão corporal culposa por acidente de trânsito', 'Total Estupro'): 1/9,
    ('Lesão corporal culposa por acidente de trânsito', 'Latrocínio'): 1/7,

    # Comparações envolvendo 'Lesão corporal culposa outras'
    ('Lesão corporal culposa outras', 'Lesão corporal dolosa'): 1,
    ('Lesão corporal culposa outras', 'Homicídio culposo por acidente de trânsito'): 1/5,
    ('Lesão corporal culposa outras', 'Homicídio culposo outros'): 1/5,
    ('Lesão corporal culposa outras', 'Tentativa de homicídio'): 1/2,
    ('Lesão corporal culposa outras', 'Homicídio doloso (nº de vítimas)'): 1/5,
    ('Lesão corporal culposa outras', 'Total Estupro'): 1/9,
    ('Lesão corporal culposa outras', 'Latrocínio'): 1/7,

    # Comparações envolvendo 'Lesão corporal dolosa'
    ('Lesão corporal dolosa', 'Homicídio culposo por acidente de trânsito'): 1/5,
    ('Lesão corporal dolosa', 'Homicídio culposo outros'): 1/5,
    ('Lesão corporal dolosa', 'Tentativa de homicídio'): 1/2,
    ('Lesão corporal dolosa', 'Homicídio doloso (nº de vítimas)'): 1/5,
    ('Lesão corporal dolosa', 'Total Estupro'): 1/9,
    ('Lesão corporal dolosa', 'Latrocínio'): 1/7,

    # Comparações envolvendo 'Homicídio culposo por acidente de trânsito'
    ('Homicídio culposo por acidente de trânsito', 'Homicídio culposo outros'): 1,
    ('Homicídio culposo por acidente de trânsito', 'Tentativa de homicídio'): 2,
    ('Homicídio culposo por acidente de trânsito', 'Homicídio doloso (nº de vítimas)'): 1,
    ('Homicídio culposo por acidente de trânsito', 'Total Estupro'): 1/2,
    ('Homicídio culposo por acidente de trânsito', 'Latrocínio'): 1,

    # Comparações envolvendo 'Homicídio culposo outros'
    ('Homicídio culposo outros', 'Tentativa de homicídio'): 2,
    ('Homicídio culposo outros', 'Homicídio doloso (nº de vítimas)'): 1,
    ('Homicídio culposo outros', 'Total Estupro'): 1/2,
    ('Homicídio culposo outros', 'Latrocínio'): 1,

    # Comparações envolvendo 'Tentativa de homicídio'
    ('Tentativa de homicídio', 'Homicídio doloso (nº de vítimas)'): 1/2,
    ('Tentativa de homicídio', 'Total Estupro'): 1/3,
    ('Tentativa de homicídio', 'Latrocínio'): 1/2,

    # Comparações envolvendo 'Homicídio doloso (nº de vítimas)'
    ('Homicídio doloso (nº de vítimas)', 'Total Estupro'): 1/2,
    ('Homicídio doloso (nº de vítimas)', 'Latrocínio'): 1,

    # Comparações envolvendo 'Total Estupro'
    ('Total Estupro', 'Latrocínio'): 2
}

# Criar o objeto AHP para Gravidade do Crime
gravidade_ahp = ahpy.Compare(
    name='Gravidade do Crime',
    comparisons=comparacoes_gravidade,
    precision=3,
    random_index='saaty'
)

# Criar o objeto AHP para Impacto Social
impacto_social_ahp = ahpy.Compare(
    name='Impacto Social',
    comparisons=comparacoes_impacto_social,
    precision=3,
    random_index='saaty'
)

# Criar o objeto AHP para os critérios principais
criterios_ahp = ahpy.Compare(
    name='Critérios',
    comparisons=comparacoes_criterios,
    precision=3,
    random_index='saaty'
)

# Adicionar os subcritérios ao AHP principal
criterios_ahp.add_children([gravidade_ahp, impacto_social_ahp])

# Verificar consistência
print(f"Consistency Ratio (Critérios): {criterios_ahp.consistency_ratio:.4f}")
if criterios_ahp.consistency_ratio > 0.1:
    print("A consistência das comparações dos critérios é baixa. Revise as comparações.")
else:
    print("A consistência das comparações dos critérios está adequada.")

# Pesos finais combinados para os crimes
pesos_finais = criterios_ahp.target_weights


print("\nPesos Globais dos Crimes (Combinação Gravidade e Impacto Social):")
for crime, peso in sorted(pesos_finais.items(), key=lambda x: x[1], reverse=True):
    print(f"{crime}: {peso:.4f}")

Consistency Ratio (Critérios): 0.0000
A consistência das comparações dos critérios está adequada.

Pesos Globais dos Crimes (Combinação Gravidade e Impacto Social):
Latrocínio: 0.1990
Homicídio doloso (nº de vítimas): 0.1920
Total Estupro: 0.1900
Tentativa de homicídio: 0.0970
Homicídio culposo outros: 0.0930
Homicídio culposo por acidente de trânsito: 0.0920
Lesão corporal dolosa: 0.0370
Lesão corporal culposa por acidente de trânsito: 0.0290
Lesão corporal culposa outras: 0.0270
Total de roubos: 0.0170
Furto de veículo: 0.0140
Furtos outros: 0.0140

In [ ]:
pesos_AHP_2 = {
    'Furto veiculo': 0.0140,
    'Furto outros': 0.0140,
    'Homicidio culposo outros': 0.093,
    'Homicidio culposo por acidente': 0.092,
    'Latrocinio':  0.1990,
    'Lesao culposa outros': 0.0270,
    'Lesao culposa acidente': 0.0290,
    'Lesao dolosa': 0.037,
    'Vitimas homicidio': 0.1920,
    'Tentativa homicidio': 0.0970,
    'Total estupro': 0.1900,
    'Total roubos': 0.0170
}

In [ ]:
dataframes = [df_2014_pop_2, df_2016_pop_2, df_2018_pop_2, df_2020_pop_2, df_2022_pop_2]

for df, ano in zip(dataframes, anos):
    df['Indice Criminalidade'] = df.apply(lambda row: calcular_indice_criminalidade(row, ano, pesos_AHP_2), axis=1)

In [ ]:
df_index_2014_2 = df_2014_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2014'})
df_index_2016_2 = df_2016_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2016'})
df_index_2018_2 = df_2018_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2018'})
df_index_2020_2 = df_2020_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2020'})
df_index_2022_2 = df_2022_pop_2[['cod_ibge', 'municipios', 'Indice Criminalidade']].rename(columns={'Indice Criminalidade': 'Indice Criminalidade 2022'})

df_final_2 = pd.concat([df_index_2014_2, df_index_2016_2['Indice Criminalidade 2016'],
                      df_index_2018_2['Indice Criminalidade 2018'],
                      df_index_2020_2['Indice Criminalidade 2020'],
                      df_index_2022_2['Indice Criminalidade 2022']], axis=1)

In [ ]:
for ano in anos:
    coluna = f'Indice Criminalidade {ano}'
    df_final_AHP_2[coluna] = df_final_AHP_2[coluna] * 1000

df_final_AHP_2

,cod_ibge,municipios,Indice Criminalidade 2014,Classificacao 2014,Indice Criminalidade 2016,Classificacao 2016,Indice Criminalidade 2018,Classificacao 2018,Indice Criminalidade 2020,Classificacao 2020,Indice Criminalidade 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.618289,Muito Baixo,0.452485,Muito Baixo,0.470704,Muito Baixo,0.264824,Muito Baixo,0.276042,Muito Baixo
1,3501905,Amparo,0.540552,Muito Baixo,0.535275,Muito Baixo,0.444223,Muito Baixo,0.248708,Muito Baixo,0.289196,Muito Baixo
2,3504107,Atibaia,0.740308,Muito Baixo,0.692443,Muito Baixo,0.504193,Muito Baixo,0.363836,Muito Baixo,0.364158,Muito Baixo
3,3507100,Bom Jesus dos Perdoes,0.455809,Muito Baixo,0.501775,Muito Baixo,0.452855,Muito Baixo,0.344605,Muito Baixo,0.461906,Muito Baixo
4,3507605,Braganca Paulista,0.684244,Muito Baixo,0.580914,Muito Baixo,0.446103,Muito Baixo,0.308601,Muito Baixo,0.362851,Muito Baixo
5,3508405,Cabreuva,0.492426,Muito Baixo,0.425934,Muito Baixo,0.366069,Muito Baixo,0.302793,Muito Baixo,0.361819,Muito Baixo
6,3509502,Campinas,0.779955,Muito Baixo,0.709133,Muito Baixo,0.605813,Muito Baixo,0.451660,Muito Baixo,0.575910,Muito Baixo
7,3509601,Campo Limpo Paulista,0.535628,Muito Baixo,0.604514,Muito Baixo,0.548921,Muito Baixo,0.339952,Muito Baixo,0.431257,Muito Baixo
8,3557303,Estiva Gerbi,0.591902,Muito Baixo,0.612906,Muito Baixo,0.452943,Muito Baixo,0.433086,Muito Baixo,0.537651,Muito Baixo
9,3519055,Holambra,0.476211,Muito Baixo,0.391664,Muito Baixo,0.325988,Muito Baixo,0.247000,Muito Baixo,0.225545,Muito Baixo
10,3520509,Indaiatuba,0.453594,Muito Baixo,0.391369,Muito Baixo,0.382405,Muito Baixo,0.270228,Muito Baixo,0.331585,Muito Baixo
11,3522604,Itapira,0.595397,Muito Baixo,0.551590,Muito Baixo,0.502731,Muito Baixo,0.392505,Muito Baixo,0.401032,Muito Baixo
12,3523404,Itatiba,0.554944,Muito Baixo,0.531935,Muito Baixo,0.441161,Muito Baixo,0.298274,Muito Baixo,0.368415,Muito Baixo
13,3524006,Itupeva,0.548324,Muito Baixo,0.507004,Muito Baixo,0.442334,Muito Baixo,0.287642,Muito Baixo,0.365646,Muito Baixo
14,3524709,Jaguariuna,0.668006,Muito Baixo,0.565796,Muito Baixo,0.596547,Muito Baixo,0.330087,Muito Baixo,0.550398,Muito Baixo
15,3525201,Jarinu,0.508688,Muito Baixo,0.439679,Muito Baixo,0.422183,Muito Baixo,0.396196,Muito Baixo,0.392450,Muito Baixo
16,3525508,Joanopolis,0.476549,Muito Baixo,0.450554,Muito Baixo,0.472477,Muito Baixo,0.292590,Muito Baixo,0.508120,Muito Baixo
17,3525904,Jundiai,0.609696,Muito Baixo,0.529851,Muito Baixo,0.424763,Muito Baixo,0.313514,Muito Baixo,0.397008,Muito Baixo
18,3527009,Lindoia,0.482347,Muito Baixo,0.511722,Muito Baixo,0.348248,Muito Baixo,0.492799,Muito Baixo,0.258726,Muito Baixo
19,3527306,Louveira,0.499429,Muito Baixo,0.449817,Muito Baixo,0.346043,Muito Baixo,0.288586,Muito Baixo,0.310378,Muito Baixo
20,3530706,Mogi Guacu,0.650160,Muito Baixo,0.662235,Muito Baixo,0.572051,Muito Baixo,0.409953,Muito Baixo,0.502747,Muito Baixo
21,3530805,Mogi Mirim,0.707875,Muito Baixo,0.652664,Muito Baixo,0.557184,Muito Baixo,0.421353,Muito Baixo,0.493286,Muito Baixo
22,3531209,Monte Alegre do Sul,0.346603,Muito Baixo,0.294690,Muito Baixo,0.288793,Muito Baixo,0.232254,Muito Baixo,0.335203,Muito Baixo
23,3532009,Morungaba,0.432687,Muito Baixo,0.350286,Muito Baixo,0.340553,Muito Baixo,0.258190,Muito Baixo,0.270361,Muito Baixo
24,3532405,Nazare Paulista,0.593294,Muito Baixo,0.601612,Muito Baixo,0.555590,Muito Baixo,0.331334,Muito Baixo,0.440781,Muito Baixo
25,3536505,Paulinia,0.706872,Muito Baixo,0.628567,Muito Baixo,0.530732,Muito Baixo,0.388378,Muito Baixo,0.491508,Muito Baixo
26,3536802,Pedra Bela,0.404302,Muito Baixo,0.408143,Muito Baixo,0.332363,Muito Baixo,0.241202,Muito Baixo,0.316734,Muito Baixo
27,3537107,Pedreira,0.599509,Muito Baixo,0.641502,Muito Baixo,0.408387,Muito Baixo,0.232898,Muito Baixo,0.266386,Muito Baixo
28,3538204,Pinhalzinho,0.360479,Muito Baixo,0.349112,Muito Baixo,0.263079,Muito Baixo,0.269565,Muito Baixo,0.325227,Muito Baixo
29,3538600,Piracaia,0.570192,Muito Baixo,0.439489,Muito Baixo,0.472395,Muito Baixo,0.308264,Muito Baixo,0.388306,Muito Baixo
30,3548005,Santo Antonio de Posse,0.467035,Muito Baixo,0.455719,Muito Baixo,0.428926,Muito Baixo,0.306639,Muito Baixo,0.382395,Muito Baixo
31,3551603,Serra Negra,0.514566,Muito Baixo,0.563502,Muito Baixo,0.423190,Muito Baixo,0.339145,Muito Baixo,0.334974,Muito Baixo
32,3552106,Socorro,0.453883,Muito Baixo,0.396726,Muito Baixo,0.360964,Muito Baixo,0.293782,Muito Baixo,0.254154,Muito Baixo
33,3554953,Tuiuti,0.549634,Muito Baixo,0.483006,Muito Baixo,0.289345,Muito Baixo,0.257744,Muito Baixo,0.359357,Muito Baixo
34,3556206,Valinhos,0.537348,Muito Baixo,0.457742,Muito Baixo,0.419102,Muito Baixo,0.312959,Muito Baixo,0.335525,Muito Baixo
35,3556354,Vargem,0.559800,Muito Baixo,0.489402,Muito Baixo,0.451602,Muito Baixo,0.294357,Muito Baixo,0.363100,Muito Baixo
36,3556503,Varzea Paulista,0.495032,Muito Baixo,0.515070,Muito Baixo,0.408334,Muito Baixo,0.321746,Muito Baixo,0.396076,Muito Baixo
37,3556701,Vinhedo,0.613778,Muito Baixo,0.469612,Muito Baixo,0.422261,Muito Baixo,0.293297,Muito Baixo,0.354843,Muito Baixo

In [ ]:
df_final_AHP_2 = df_final_AHP_2.copy()

for ano in anos:
    coluna_index = f'Indice Criminalidade {ano}'
    coluna_classificacao = f'Classificacao {ano}'
    df_final_AHP_2[coluna_classificacao] = pd.cut(df_final_AHP_2[coluna_index], bins=bins, labels=labels, include_lowest=True)

df_final_AHP_2 = df_final_AHP_2[['cod_ibge', 'municipios', 'Indice Criminalidade 2014', 'Classificacao 2014', 'Indice Criminalidade 2016',
                                 'Classificacao 2016', 'Indice Criminalidade 2018', 'Classificacao 2018', 'Indice Criminalidade 2020',
                                 'Classificacao 2020', 'Indice Criminalidade 2022', 'Classificacao 2022']]
df_final_AHP_2.head(3)

,cod_ibge,municipios,Indice Criminalidade 2014,Classificacao 2014,Indice Criminalidade 2016,Classificacao 2016,Indice Criminalidade 2018,Classificacao 2018,Indice Criminalidade 2020,Classificacao 2020,Indice Criminalidade 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.618289,Alto,0.452485,Médio,0.470704,Médio,0.264824,Baixo,0.276042,Baixo
1,3501905,Amparo,0.540552,Médio,0.535275,Médio,0.444223,Médio,0.248708,Baixo,0.289196,Baixo
2,3504107,Atibaia,0.740308,Alto,0.692443,Alto,0.504193,Médio,0.363836,Baixo,0.364158,Baixo

# Comparação de resultados

In [ ]:
df_normalizado.head()

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Classificacao 2014,Indice Criminalidade Normalizado 2016,Classificacao 2016,Indice Criminalidade Normalizado 2018,Classificacao 2018,Indice Criminalidade Normalizado 2020,Classificacao 2020,Indice Criminalidade Normalizado 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.574364,Médio,0.302664,Baixo,0.463143,Médio,0.010731,Muito Baixo,0.120750,Muito Baixo
1,3501905,Amparo,0.461050,Médio,0.532752,Médio,0.476568,Médio,0.000000,Muito Baixo,0.149246,Muito Baixo
2,3504107,Atibaia,0.912955,Muito Alto,1.000000,Muito Alto,0.757941,Alto,0.710423,Alto,0.312955,Baixo
3,3507100,Bom Jesus dos Perdoes,0.207810,Baixo,0.342858,Baixo,0.347719,Baixo,0.203446,Baixo,0.354005,Baixo
4,3507605,Braganca Paulista,0.827855,Muito Alto,0.697786,Alto,0.612861,Alto,0.487620,Médio,0.404535,Médio

In [ ]:
df_normalizado_2.head()

,cod_ibge,municipios,Indice Criminalidade Normalizado 2014,Classificacao 2014,Indice Criminalidade Normalizado 2016,Classificacao 2016,Indice Criminalidade Normalizado 2018,Classificacao 2018,Indice Criminalidade Normalizado 2020,Classificacao 2020,Indice Criminalidade Normalizado 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.563033,Médio,0.335446,Baixo,0.480963,Médio,0.013998,Muito Baixo,0.113259,Muito Baixo
1,3501905,Amparo,0.465091,Médio,0.580210,Médio,0.513114,Médio,0.022164,Muito Baixo,0.125659,Muito Baixo
2,3504107,Atibaia,0.825387,Muito Alto,0.916372,Muito Alto,0.640838,Alto,0.504822,Médio,0.344794,Baixo
3,3507100,Bom Jesus dos Perdoes,0.263848,Baixo,0.464167,Médio,0.493944,Médio,0.353559,Baixo,0.412630,Médio
4,3507605,Braganca Paulista,0.780567,Alto,0.680555,Alto,0.568227,Médio,0.386751,Baixo,0.387877,Baixo

In [ ]:
df_final_AHP.head()

,cod_ibge,municipios,Indice Criminalidade 2014,Classificacao 2014,Indice Criminalidade 2016,Classificacao 2016,Indice Criminalidade 2018,Classificacao 2018,Indice Criminalidade 2020,Classificacao 2020,Indice Criminalidade 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.612733,Alto,0.457943,Médio,0.463043,Médio,0.256759,Baixo,0.271026,Baixo
1,3501905,Amparo,0.539460,Médio,0.523800,Médio,0.435118,Médio,0.243862,Baixo,0.285714,Baixo
2,3504107,Atibaia,0.727712,Alto,0.678808,Alto,0.494566,Médio,0.356432,Baixo,0.357189,Baixo
3,3507100,Bom Jesus dos Perdoes,0.450033,Médio,0.495885,Médio,0.446898,Médio,0.337375,Baixo,0.452092,Médio
4,3507605,Braganca Paulista,0.679705,Alto,0.575458,Médio,0.440645,Médio,0.306480,Baixo,0.358364,Baixo

In [ ]:
df_final_AHP_2.head()

,cod_ibge,municipios,Indice Criminalidade 2014,Classificacao 2014,Indice Criminalidade 2016,Classificacao 2016,Indice Criminalidade 2018,Classificacao 2018,Indice Criminalidade 2020,Classificacao 2020,Indice Criminalidade 2022,Classificacao 2022
0,3500501,Aguas de Lindoia,0.618289,Alto,0.452485,Médio,0.470704,Médio,0.264824,Baixo,0.276042,Baixo
1,3501905,Amparo,0.540552,Médio,0.535275,Médio,0.444223,Médio,0.248708,Baixo,0.289196,Baixo
2,3504107,Atibaia,0.740308,Alto,0.692443,Alto,0.504193,Médio,0.363836,Baixo,0.364158,Baixo
3,3507100,Bom Jesus dos Perdoes,0.455809,Médio,0.501775,Médio,0.452855,Médio,0.344605,Baixo,0.461906,Médio
4,3507605,Braganca Paulista,0.684244,Alto,0.580914,Médio,0.446103,Médio,0.308601,Baixo,0.362851,Baixo